make osxcross optional (#16)
Co-authored-by: CrazyMax <crazy-max@users.noreply.github.com>

diff --git a/rootfs/usr/local/bin/goxx-macports b/rootfs/usr/local/bin/goxx-macports
--- a/rootfs/usr/local/bin/goxx-macports
+++ b/rootfs/usr/local/bin/goxx-macports
@@ -6,9 +6,14 @@ set -e
 
 source goxx-env
 
-if [ "${GOOS}" != "darwin" ]; then
-  exit 0
-fi
+exitnodarwin() {
+  if [ "${GOOS}" != "darwin" ]; then
+    echo >&2 "WARN: skipping macports on ${GOOS}"
+    exit 0
+  fi
+}
+
+exitnodarwin
 
 if [ -z "$MACOSX_DEPLOYMENT_TARGET" ]; then
   export MACOSX_DEPLOYMENT_TARGET=10.10
@@ -16,8 +21,6 @@ if [ -z "$MACOSX_DEPLOYMENT_TARGET" ]; then
     export MACOSX_DEPLOYMENT_TARGET=11.2
   fi
 fi
-
-echo 1 | osxcross-macports select-mirror >/dev/null 2>&1 || true
 
 packages=
 parsed=
@@ -59,6 +62,13 @@ flags=""
 if [ "${GOARCH}" = "arm64" ]; then
   flags="--arm64"
 fi
+
+if ! command -v "osxcross-macports" >/dev/null 2>/dev/null; then
+  echo >&2 'WARN: osxcross-macports command not found. Is osxcross installed?'
+  exit 0
+fi
+
+echo 1 | osxcross-macports select-mirror >/dev/null 2>&1 || true
 
 set -x
 exec osxcross-macports $flags "$@"
